
version: '3.7'
networks:
  development:
  test:
volumes:
  db_data:
  gem_cache:
  shared_data:
services:
  redis:
    image: redis:4.0-alpine
    command: redis-server
    networks:
      - development
      - test
    volumes:
      - shared_data:/var/shared/redis
  presupuestos_investigacion_db:
    image: postgres:12.7-alpine
    container_name: presupuestos_investigacion_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - shared_data:/var/shared
    networks:
      - development
      - test
    environment:
      POSTGRES_USER: uniremington_user
      POSTGRES_PASSWORD: admin
      POSTGRES_PORT: 5432
    ports:
      - 5434:5432
  presupuestos_web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: presupuestos_web
    volumes:
      - .:/var/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    networks:
      - development
    ports:
      - 3010:3010
    stdin_open: true
    tty: true
    env_file: .env.development
    entrypoint: dev-entrypoint.sh
    command: ['rails', 'server', '-p', '3010', '-b', '0.0.0.0']
    environment:
      RAILS_ENV: development
    depends_on:
      - presupuestos_investigacion_db
  presupuestos_web_test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: presupuestos_web_test
    volumes:
      - .:/var/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    networks:
      - test
    ports:
      - 3011:3010
    stdin_open: true
    tty: true
    env_file: .env.test
    entrypoint: test-entrypoint.sh
    command: ["rails", "-v"]
    environment:
      RAILS_ENV: test
    depends_on:
      - presupuestos_investigacion_db
